Repository googleapis/java-containeranalysis, pull requests merged in 2020-06, with the labels that each got.

#160 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, automerge, cla: yes, context: none

#163 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, automerge, cla: yes, context: full

#165 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, automerge, cla: yes, context: full

#167 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, automerge, cla: yes, context: full

#172 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, automerge, cla: yes, context: none

#173 feat: promote to GA
  .repo-metadata.json
  README.md
Labels: cla: yes

#178 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, automerge, cla: yes, context: none

#182 ci: switch to secret manager for samples/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, automerge, cla: yes, context: full

#184 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-containeranalysis/pom.xml
  grpc-google-cloud-containeranalysis-v1/pom.xml
  grpc-google-cloud-containeranalysis-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-containeranalysis-v1/pom.xml
  proto-google-cloud-containeranalysis-v1beta1/pom.xml
Labels: cla: yes

#188 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, automerge, cla: yes, context: none

#194 fix: migrate to grpc_service_config
  README.md
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/stub/ContainerAnalysisStubSettings.java
  synth.metadata
Labels: automerge, automerge, cla: yes, context: partial

#200 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, automerge, cla: yes, context: none
