Repository googleapis/java-containeranalysis, pull requests merged in 2020-12, with the labels that each got.

#354 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: containeranalysis, automerge, automerge, cla: yes, context: full

#345 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#357 chore: update CODEOWNERS
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: containeranalysis, automerge, automerge, cla: yes

#355 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#360 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#361 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#358 chore: Re-generated to pick up changes from self.
  .github/CODEOWNERS
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: none

#367 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#375 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#377 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#379 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: containeranalysis, automerge, automerge, cla: yes, context: full

#380 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: containeranalysis, automerge, automerge, cla: yes, context: full, merge
