Repository googleapis/java-containeranalysis, pull requests merged in 2020-09, with the labels that each got.

#238 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: full

#241 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, automerge, cla: yes, context: none

#255 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, automerge, cla: yes, context: none

#257 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, automerge, cla: yes, context: full

#258 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: containeranalysis, automerge, automerge, cla: yes

#263 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, automerge, cla: yes, context: full

#266 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, automerge, cla: yes, context: full
