Repository googleapis/java-containeranalysis, pull requests merged in 2021-07, with the labels that each got.

#609 chore: release gapic-generator-java v1.0.13
  proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/ProjectName.java
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: full

#611 fix: Add `shopt -s nullglob` to dependencies script
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: full

#618 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, cla: yes

#619 chore: remove distributionManagement section
  pom.xml
Labels: api: containeranalysis, automerge, cla: yes

#620 chore: remove distributionManagement section
  google-cloud-containeranalysis-bom/pom.xml
Labels: api: containeranalysis, automerge, cla: yes

#623 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, cla: yes

#622 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: containeranalysis, automerge, cla: yes, context: full

#624 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: containeranalysis, automerge, cla: yes, context: full

#625 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, cla: yes

#627 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, cla: yes

#630 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, cla: yes

#633 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: containeranalysis, automerge, cla: yes

#634 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: api: containeranalysis, automerge, cla: yes
