Repository googleapis/java-containeranalysis, pull requests merged in 2021-09, with the labels that each got.

#689 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, kokoro:force-run, api: containeranalysis, automerge, context: full

#694 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, kokoro:force-run, api: containeranalysis, automerge

#692 chore(java): update windows build
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: containeranalysis, context: full

#688 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: containeranalysis, automerge

#697 chore: Update sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: containeranalysis

#699 chore: re-generated to pick up changes from synthtool
  .github/trusted-contribution.yml
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, api: containeranalysis, context: partial

#695 chore: re-generated to pick up changes from self
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: containeranalysis, context: none

#718 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: containeranalysis, automerge

#719 chore(java): remove dependencyDashboardLabel config from renovate.json
  renovate.json
  synth.metadata
Labels: cla: yes, api: containeranalysis, context: full

#721 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: containeranalysis

#720 chore: re-generated to pick up changes from synthtool
  .github/blunderbuss.yml
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, api: containeranalysis, context: full
