Repository googleapis/java-containeranalysis, pull requests merged in 2021-02, with the labels that each got.

#395 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#378 chore: stop generating the v1beta1 client
  synth.metadata
  synth.py
Labels: api: containeranalysis, cla: yes

#398 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: containeranalysis, cla: yes

#399 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#401 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: containeranalysis, automerge, automerge, cla: yes, context: full

#402 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, automerge, cla: yes, context: full

#406 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#405 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: containeranalysis, automerge, automerge, cla: yes, context: full

#408 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: containeranalysis, automerge, automerge, cla: yes, context: full

#413 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#447 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: containeranalysis, automerge, automerge, cla: yes, context: full

#449 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: containeranalysis, automerge, automerge, cla: yes, context: full

#450 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: containeranalysis, automerge, automerge, cla: yes, context: full

#400 chore: migrate containeranalysis to the Java microgenerator
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/ContainerAnalysisClient.java
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/ContainerAnalysisSettings.java
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/package-info.java
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/stub/ContainerAnalysisStub.java
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/stub/ContainerAnalysisStubSettings.java
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/stub/GrpcContainerAnalysisCallableFactory.java
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/stub/GrpcContainerAnalysisStub.java
  google-cloud-containeranalysis/src/test/java/com/google/cloud/devtools/containeranalysis/v1/ContainerAnalysisClientTest.java
  google-cloud-containeranalysis/src/test/java/com/google/cloud/devtools/containeranalysis/v1/MockContainerAnalysis.java
  google-cloud-containeranalysis/src/test/java/com/google/cloud/devtools/containeranalysis/v1/MockContainerAnalysisImpl.java
  proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/ProjectName.java
Labels: api: containeranalysis, cla: yes, context: full

#451 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#454 docs: generate samples in gapic client classes
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/ContainerAnalysisClient.java
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/package-info.java
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/stub/GrpcContainerAnalysisStub.java
  google-cloud-containeranalysis/src/test/java/com/google/cloud/devtools/containeranalysis/v1/MockContainerAnalysisImpl.java
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: partial

#462 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#463 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#464 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/gapic_metadata.json
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: full

#466 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#468 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#474 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes

#477 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, automerge, cla: yes
