Repository googleapis/java-containeranalysis, pull requests merged in 2021-08, with the labels that each got.

#631 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: containeranalysis, automerge, context: full

#640 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: containeranalysis, automerge

#637 feat!: release gapic-generator-java v2.0.0
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/ContainerAnalysisSettings.java
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/stub/ContainerAnalysisStubSettings.java
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/stub/GrpcContainerAnalysisStub.java
  synth.metadata
Labels: cla: yes, api: containeranalysis, automerge, context: full

#650 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: containeranalysis, automerge

#651 chore: release gapic-generator-java v2.0.1
  google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/package-info.java
  synth.metadata
Labels: cla: yes, api: containeranalysis, automerge, context: full

#654 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: containeranalysis, automerge, context: full

#661 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: containeranalysis, automerge

#662 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: containeranalysis, automerge

#664 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: containeranalysis, automerge

#673 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: containeranalysis, automerge

#671 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: containeranalysis, automerge

#675 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: containeranalysis, automerge

#677 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: containeranalysis, automerge

#684 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: containeranalysis, context: full
